@url = http://localhost:3001/api
@url2 = http://42.193.157.90:3001/api
@json = Content-Type: application/json

###
post {{url}}/articles
{{json}}

{
  "name":"第4篇文章",
  "body":"文章内容"
}

###
get {{url}}/articles/60460341fcca9c08fc9d36a7


###
post {{url2}}/articles
{{json}}

{
  "name":"服务器",
  "body":"服务器啊"
}